version: '3.2'
services:
  dino-eval:
    image: davis2017-eval
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # command: jupyter lab --ip=0.0.0.0 --port 8888 --no-browser --allow-root
    command: bash
    # ports:
    # - 8888:8888
    volumes:
      - type: bind
        target: /workspace/datasets
        source: K:/datasets
        read_only: true
      - type: bind
        target: /workspace/results
        source: K:/results-dino
        read_only: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]